config/routes.rb
Ajaxtodo::Application.routes.draw do
  root :to => 'home#index'

  resources :priorities, only: [:new, :create]

  resources :tasks do
    member do
      put :arrow_up
      put :arrow_down
    end
  end  
end

app/models/priority.rb
class Priority < ActiveRecord::Base
  attr_accessible :name, :urgency_index, :color

  has_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :desc, :duedate, :name, :priority_id

  belongs_to :priority

  def arrow_up
    current_urgency = self.priority.urgency_index

    higher_priorities = Priority.where('urgency_index > ?', current_urgency)
    if higher_priorities.any?
      self.priority = higher_priorities.first(order: 'urgency_index ASC')
      self.save
    end
    self.priority
  end

  def arrow_down
    current_urgency = self.priority.urgency_index

    lower_priorities = Priority.where('urgency_index < ?', current_urgency)
    if lower_priorities.any?
      self.priority = lower_priorities.first(order: 'urgency_index DESC')
      self.save
    end
    self.priority
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @tasks = Task.all
    @priorities = Priority.all
  end
end

app/controllers/priorities_controller.rb
class PrioritiesController < ApplicationController

  def new
    @priority = Priority.new
    @priorities = Priority.all
  end

  def create
    @priority = Priority.new(params[:priority])
    @priority.save!
    render :json => @priority  
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	
	before_filter :ordered_tasks, only: [:new, :update]

	def new
		@task = Task.new
		@priorities = Priority.all
	end

	def create
		@task = Task.new(params[:task])
		@task.save!
		render json: {task: @task, priority: @task.priority}
	end

	def index
		@tasks = Task.all
	end

	def update
		@task = Task.find(params[:id])
		if @task.update_attributes(params[:task])
			# render json: {task: @task, priority: @task.priority}
			respond_to do |format|
				format.js
			end
		else
			respond_to do |format|
				format.js { render status: 500, text: 'Server error'}
			end
		end
	end

	def destroy
		# get the id of the item we wish to destroy
		task = Task.find(params[:id])
		task.destroy 
		# need to delete it from the database
		# need to render some sort of response or redirect
		render json: task
	end

	def arrow_up
		@task = Task.find(params[:id])
		@task.arrow_up
		render json: @task.priority
	end

	def arrow_down
		@task = Task.find(params[:id])
		@task.arrow_down
		render json: @task.priority
	end

	private
	def ordered_tasks
		@tasks = Task.joins(:priority).order('priorities.urgency_index DESC, name ASC' )
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
.row
  .large-6.columns.small-12
    %table#list
      %thead
        %th Name
        %th Description
        %th Due Date
        %th Priority ID
      %tbody
        - @tasks.each do |t|
          %tr.task{style: 'background-color:' +t.priority.color}
            %td= t.name
            %td= t.desc
            %td= t.duedate
            %td= t.priority_id
  .large-6.columns.small-12            
    %table#priorities
      %tbody
      - @priorities.each do |x|
        %tr.priority
          %td= x.name
          %td= x.urgency_index
          %td= x.color
          %td{style: "background-color: #{x.color}"} 

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Ajaxtodo
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = javascript_include_tag "ui-extra", :src => 'http://code.jquery.com/ui/1.10.3/jquery-ui.js'
    = csrf_meta_tags
  %body
    = render partial: 'layouts/partials/nav'
    .row
      = yield
    / Foundation initialization javascript
    :javascript
      $(document).foundation();
    

app/views/layouts/partials/_nav.html.haml
%nav.top-bar
  %ul.title-area
    / Title Area
    %li.name
      %h1
        %a{:href => "/"} To Do List
    %li.toggle-topbar.menu-icon
      %a{:href => "#"}
        %span Menu
  %section.top-bar-section
    / Left Nav Section
    %ul.left
      %li.divider
      %li.active
        %a{:href => "/tasks/new"} New Item To Do
      %li.divider
      %li
        %a{:href => "/priorities/new"} Priorities List
      %li.divider
      %li.divider
/ End Foundation

app/views/priorities/new.html.haml
= form_for @priority do |f|
  = f.label :name
  = f.text_field :name
  = f.label :urgency_index
  = f.text_field :urgency_index 
  
  = f.label :color
  / = f._field :color
  %input#priority_color{type: 'color', name: 'priority[color]'}

  = f.submit id: 'get_priority'

%table#list
  %thead
    %th Priority Name
    %th Priority Urgency
    %th Priority Color 
  %tbody
    - @priorities.each do |x|
      %tr.priority
        %td= x.name
        %td= x.urgency_index
        %td= x.color
        %td{style: "background-color: #{x.color}"}  

= javascript_include_tag 'priorities'

app/views/tasks/arrow_down.js.erb
$('#tasks tbody').empty().append("<%=j render partial: 'tasks/partials/tasks' %>");

var task_row = $('#tasks tr[data-task-id=' + task_id + ']');
task_row.children('td.priority-id').text(data.id);
task_row.children('td.ui').text(data.urgency_index);
task_row.animate({backgroundColor: data.color});
sort_rows();

app/views/tasks/index.html.haml
%table#list
  %tbody
    - @tasks.each do |t|
      %tr.task
        %td= t.name
        %td= t.desc
        %td= t.duedate
        %td= t.priority_id

app/views/tasks/new.html.haml
= form_for @task do |f|
  = f.label :name
  = f.text_field :name
  = f.label :desc
  = f.text_field :desc
  = f.label :duedate
  = f.text_field :duedate
  = f.label :priority_id
  = f.collection_select :priority_id, @priorities, :id, :name, include_blank: true, prompt: '-- Choose Priority --'
  = f.submit id: 'submit', class: 'button success small'
  = f.submit id: 'edit-submit', class: 'button small hidden', value: 'Update Task'

%table#tasks
  %thead
    %th#name
      =link_to 'Name', '#', id: 'name-sort'
    %th#description
      =link_to 'Description', '#', id: 'desc-sort'
    %th#duedate
      =link_to 'Due Date', '#', id: 'duedate-sort'
    / %th Priority ID
    %th#ui
      =link_to 'Urgency Index', '#', id: 'ui-sort'
    %th#options
      =link_to 'Options', '#'
    %th#arrows
      %p{class: 'general foundicon-up-arrow'}
      %p{class: 'general foundicon-down-arrow'}
  %tbody
    = render partial: 'tasks/partials/tasks'
             
= javascript_include_tag 'tasks'

app/views/tasks/partials/_tasks.html.haml
- @tasks.each do |t|
  %tr{:'data-task-id' => t.id, style: "background-color: #{t.priority.color}"}
    / class: "priority_#{t.priority.id}"
    %td.name
      = t.name
    %td.desc
      = t.desc
    %td.duedate
      = t.duedate
    %td.ui
      = t.priority.urgency_index
    %td.priority-id{style: 'display: none;'}
      = t.priority.id
    %td.options
      =link_to 'Delete', "#{t.id}", class: 'small alert button delete-button'
      =link_to 'Edit', "#", class: 'small button edit-button info'
    %td.arrows  
      = link_to arrow_up_task_path(t), class: 'up-arrow-link' do
        %i.general.foundicon-up-arrow
      = link_to arrow_down_task_path(t), class: 'down-arrow-link' do
        %i.general.foundicon-down-arrow

app/views/tasks/update.js.erb
$('#tasks tbody').empty().append("<%=j render partial: 'tasks/partials/tasks' %>");

var task_row = $('#tasks tr[data-task-id='+ task_id+']')
task_row.hide()
  // Add a for loop to find the id, then call data[i]
var task = $('<tr>').attr('data-task-id', data.task.id).css('background-color', data.priority.color);
$('<td class="name">').text(data.task.name).appendTo(task);
$('<td class="desc">').text(data.task.desc).appendTo(task);
$('<td class="duedate">').text(data.task.duedate).appendTo(task);
$('<td class="ui">').text(data.priority.urgency_index).appendTo(task);
$('<td class="priority-id">').text(data.priority.id).hide().appendTo(task);

var data_cell_options = $('<td>').addClass('options');
var edit_button = $('<a>').attr('href', '#').text('Edit').addClass('small button edit-button info');
var delete_button = $('<a>').attr('href', '#').text('Delete').addClass('small alert button delete-button');
//  add data id to our delete buttong
delete_button.attr('data-task-id', data.task.id)
edit_button.attr('data-task-id', data.task.id)
data_cell_options.append(delete_button)
data_cell_options.append(edit_button)

task.append(data_cell_options)
//bind the delete functionality to the newly created button
bind_delete_button_action_to(delete_button)
bind_edit_button_to(edit_button)
add_node(task)